name: Deploy App

on:
  push:
    branches: main

defaults:
  run:
    working-directory: app

jobs:
  deploy:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
      SOURCE_DIR: app/dist
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install
        run: yarn install
      - name: build
        run: yarn build
      - name: deploy
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
