name: deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    env:
      BUCKET: adote.se
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: sa-east-1
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        working-directory: app
        run: yarn install
      - name: build
        working-directory: app
        run: yarn build
      - name: deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: out
          bucket: ${{ env.BUCKET }}
          bucket-region: ${{ env.AWS_DEFAULT_REGION }}
          delete-removed: true
