name: deploy

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: oreo

jobs:
  deploy:
    env:
      BUCKET: adote.se
      AWS_DEFAULT_REGION: sa-east-1
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install
        run: yarn install
      - name: build
        run: yarn build
      - name: export
        run: yarn export
      - name: deploy
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ env.BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_DEFAULT_REGION }}
          SOURCE_DIR: 'out'
        with:
          args: --delete
