name: main

on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: oreo
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BUCKET: adote.se
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: sa-east-1
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: yarn install
      - name: build
        run: yarn build
      - name: export
        run: yarn export
      - name: deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: out
          bucket: ${{ env.BUCKET }}
          bucket-region: ${{ env.AWS_DEFAULT_REGION }}
